Database triggers
windmill-labs/windmill pull request #4860
Opened 2024-12-05 20:12 UTC by dieriba

PostgreSQL database trigger implementation that captures transaction events (INSERT, UPDATE, DELETE). Currently, the implementation identifies the type of transaction.

Currently working on decoding the trigger message to extract detailed information about the underlying data that caused the trigger to fire.

2024-12-22 22:32 UTC, dieriba commented
I have read the CLA Document and I hereby sign the CLA

2024-12-22 22:35 UTC, dieriba commented
I have read the CLA Document and I hereby sign the CLA

2024-12-22 22:35 UTC, dieriba commented
recheck

2024-12-22 22:42 UTC, dieriba commented
I have read the CLA Document and I hereby sign the CLA

2024-12-22 22:42 UTC, dieriba commented
recheck

2024-12-22 23:09 UTC, dieriba commented
I have read the CLA Document and I hereby sign the CLA

2024-12-22 23:09 UTC, dieriba commented
recheck

2025-01-09 19:20 UTC, HugoCasa requested changes
- we need to review the frontend/UX together, i'm not sure to understand everything
- can you put the source for the code that was taken from pg_replicate? will make it easier to maintain

2025-01-09 19:20 UTC, hugocasa commented on backend/Cargo.toml
> +rust-postgres = { package = "tokio-postgres", git = "https://github.com/imor/rust-postgres", rev = "20265ef38e32a06f76b6f9b678e2077fc2211f6b"}
do you know why they use this specific version?

2025-01-09 19:20 UTC, hugocasa commented on backend/windmill-api/Cargo.toml
> +rust_decimal.workspace = true
can you make all these deps optional and put them under a database trigger feature? you will also need to put the code under the same feature

2025-01-09 19:20 UTC, hugocasa commented on backend/windmill-api/openapi.yaml
> +  /w/{workspace}/database_triggers/get-template-script:
don't use dashes, we're using underscores everywhere else

2025-01-09 19:20 UTC, hugocasa commented on frontend/src/lib/components/graph/renderers/triggers/TriggersBadge.svelte
> +		| 'websockets' | 'database'
bad formatting

2025-01-09 19:20 UTC, hugocasa commented on frontend/src/lib/components/graph/util.ts
> +	width: 285,
that's gonna change all nodes width, we don't want that, we need to change the UI, we'll discuss it

2025-01-09 19:20 UTC, hugocasa commented on backend/migrations/20241123152203_database_triggers.up.sql
> +    CONSTRAINT PK_database_trigger PRIMARY KEY (path,workspace_id)
add a foreign key constraint on workspace_id with on delete cascade

2025-01-09 19:20 UTC, hugocasa commented on backend/migrations/20241123152203_database_triggers.up.sql
> +CREATE TYPE transaction AS ENUM ('Insert', 'Update', 'Delete');
change the name to something specific to database_triggers (e.g. database_trigger_transaction)

2025-01-09 19:20 UTC, hugocasa commented on backend/windmill-common/src/resource.rs
> +    let val: T = serde_json::from_value(resource.value).unwrap();
that can panic

2025-01-09 19:20 UTC, hugocasa commented on backend/windmill-common/src/scripts.rs
better if put in another PR

2025-01-09 19:20 UTC, hugocasa commented on backend/windmill-api/src/database_triggers/handler.rs
you're missing auth for a bunch of these APIs
also you should use authed to get the resource with get_resource_value_interpolated_internal

2025-01-09 19:20 UTC, hugocasa commented on backend/windmill-common/src/resource.rs
> +    let val: T = serde_json::from_value(resource.value).unwrap();
anyway you will probably get rid of this file and use get_resource_value_interpolated_internal with authed

2025-01-09 23:58 UTC, dieriba commented on backend/Cargo.toml
> +rust-postgres = { package = "tokio-postgres", git = "https://github.com/imor/rust-postgres", rev = "20265ef38e32a06f76b6f9b678e2077fc2211f6b"}
because it implement postgres copy both query which is needed to make the logical replication protocol works

2025-01-09 23:59 UTC, dieriba commented on backend/windmill-api/Cargo.toml
> +rust_decimal.workspace = true
done

2025-01-10 08:58 UTC, HugoCasa commented on backend/windmill-api/src/database_triggers/trigger.rs
> +    let resource = sqlx::query_scalar!(
you should also use get_resource_value_interpolated here. You can use fetch_api_authed with the trigger editor/email fields

2025-01-17 18:14 UTC, HugoCasa requested changes
- fix conflicts with main
- all checks should pass (might have to revert the encrypt/script lang changes)

2025-01-17 18:14 UTC, HugoCasa commented on frontend/src/lib/components/sidebar/SidebarContent.svelte
>  		{
better if NATS and Kafka are next to each other

2025-01-17 18:14 UTC, HugoCasa commented on frontend/openapi-ts-error-1736864987786.log
delete that

2025-01-17 18:14 UTC, HugoCasa commented on backend/windmill-common/src/scripts.rs
i'm not sure those changes won't break ee

2025-01-17 18:14 UTC, HugoCasa commented on backend/windmill-api/src/database_triggers/handler.rs
> +    language: Language,
you don't need the check, it's already done by Deserialize when using the Language type

2025-01-19 12:49 UTC, dieriba commented on backend/windmill-api/src/database_triggers/handler.rs
> +    language: Language,
u're right removing it I wanted to handle the case where then name would be right, but the case would not match (found a cleaner way)

2025-01-20 13:24 UTC, uael commented on backend/windmill-api/src/database_triggers/replication_message.rs
> +struct Buffer {
`std::io::Cursor<Bytes>` could work ? [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=f147329e8068e91838e84ef6df6cbcea)

2025-01-20 13:24 UTC, uael commented on backend/windmill-api/src/database_triggers/replication_message.rs
> +        match memchr(0, self.slice()) {
```suggestion
        match self.slice().iter().position(|&x| x == 0) {
```

2025-01-20 13:24 UTC, uael commented on backend/windmill-api/src/database_triggers/bool.rs
> +    if s == "t" {
nit: could be a `match`

2025-01-20 13:24 UTC, uael commented on backend/windmill-api/src/database_triggers/converter.rs
> +        let value = match typ {
```suggestion
        let value = match typ.unwrap_or(&Type::TEXT) {
```

2025-01-20 13:24 UTC, uael commented on backend/windmill-api/src/database_triggers/handler.rs
> +            now()
could be elided if set as default in the table

2025-01-20 13:24 UTC, uael commented on backend/windmill-api/src/database_triggers/handler.rs
> +    let mut query = QueryBuilder::new("DROP PUBLICATION IF EXISTS ");
nit: use `format!`

2025-01-20 13:24 UTC, uael commented on backend/windmill-api/src/database_triggers/handler.rs
> +pub struct Database {
nit: remove `pub` visibility if only used in this module, same for other

2025-01-20 13:24 UTC, uael commented on backend/windmill-api/src/database_triggers/handler.rs
> +
nit: remove empty line

2025-01-20 13:24 UTC, uael commented on backend/windmill-api/src/database_triggers/handler.rs
> +            pg_create_logical_replication_slot({}, 'pgoutput');"#,
nit: can't this be a prepared query and use `sqlx::query!` ?

2025-01-20 13:24 UTC, uael commented on backend/windmill-api/src/database_triggers/handler.rs
> +    let query = format!("SELECT pg_drop_replication_slot({});", quote_literal(&name));
nit: can't this be a prepared query and use `sqlx::query!` ?

2025-01-20 13:24 UTC, uael commented on backend/windmill-api/src/database_triggers/handler.rs
> +    let publication_names = sqlx::query_as!(
nit: use `sqlx::query_scalar!` -> `sqlx::query_scalar!("SELECT pubname FROM pg_publication")`
so next `.map(...)` and `PublicationName` struct can be removed

2025-01-20 13:24 UTC, uael commented on backend/windmill-api/src/database_triggers/handler.rs
> +    let transaction = sqlx::query_as!(
nit: use `sqlx::query`:
```rust
    let transaction = sqlx::query!(
        ...,
        publication_name
    )
    .fetch_one(&mut *connection)
    .await?;
```
and remove `PublicationTransaction`

2025-01-20 13:24 UTC, uael commented on backend/windmill-api/src/database_triggers/handler.rs
> +    let publications = sqlx::query_as!(
nit: Same as above
and since most of them are required:
```rust
    let publications = sqlx::query!(
        r#"
            SELECT
                schemaname AS "schema_name!: String",
                tablename AS "table_name!: String",
                attnames AS "columns!: String",
                rowfilter AS where_clause
            FROM
                pg_publication_tables
            WHERE
                pubname = $1
            "#,
        publication_name
    )
    .fetch_all(&mut *connection)
    .await?;
```
and the WHERE could filter null values if necessary

2025-01-20 13:24 UTC, uael commented on backend/windmill-api/src/database_triggers/handler.rs
> +        let schema_name = publication.schema_name.unwrap();
```suggestion
        let Some(schema_name) = publication.schema_name else { continue };
```

2025-01-20 13:24 UTC, uael commented on backend/windmill-api/src/database_triggers/handler.rs
> +            UPDATE database_trigger
nit: indent left

2025-01-20 13:24 UTC, uael commented on backend/windmill-api/src/database_triggers/handler.rs
> +    let query = format!(
I think this could be checked as well using `sqlx::query!` with `unnest($1::TEXT[])`, but I'm not sure

2025-01-20 13:24 UTC, uael commented on backend/windmill-api/src/database_triggers/handler.rs
> +    let is_logical = match wal_level.as_deref() {
nit: `wal_level.as_deref() == Some("logical")`

2025-01-20 13:24 UTC, uael commented on backend/windmill-api/src/database_triggers/mapper.rs
> +    let data_type = match postgres_type {
```suggestion
    let data_type = match postgres_type.unwrap_or(Type::TEXT) {
```

2025-01-20 13:24 UTC, uael commented on backend/windmill-api/src/database_triggers/replication_message.rs
> +use core::str;
nit: `std::str`
not included by default ?

2025-01-20 13:24 UTC, uael commented on backend/windmill-api/src/database_triggers/trigger.rs
> +impl RowExist for Vec<SimpleQueryMessage> {
nit: if used only once it might be prefered to just use a function instead `fn row_exist(vec: &Vec<SimpleQueryMessage>) -> bool`

2025-01-20 13:24 UTC, uael commented on backend/windmill-api/src/database_triggers/trigger.rs
> +        tokio::spawn(async move {
Add a comment why spawned and not directly awaited

2025-01-20 13:24 UTC, uael commented on backend/windmill-api/src/database_triggers/trigger.rs
> +                r#"("proto_version" '2', "publication_names" {})"#,
indentation (or `cargo fmt` 👀)

2025-01-20 13:24 UTC, uael commented on backend/windmill-api/src/database_triggers/trigger.rs
> +    match sqlx::query_scalar!(
For readability it's prefered to:
```rust
let updated = match ... { Ok(updated) => updated, Err(err) => return ... };
...
```

2025-01-20 13:24 UTC, uael commented on backend/windmill-api/src/database_triggers/trigger.rs
> +        if update_ping(db, database_trigger, error).await.is_none() {
I would dispatch the error through `update_ping` and move the `warn!` here instead. So it's easier to understand why the loop is stopped

2025-01-20 13:24 UTC, uael commented on backend/windmill-api/src/database_triggers/trigger.rs
> +    tokio::spawn(async move {
async fn that spawn w/o await points

2025-01-20 13:24 UTC, uael commented on backend/windmill-api/src/variables.rs
> +    let mut variable = sqlx::query_as!(
nit: use `sqlx::query!` and remove `Variable`

2025-01-21 23:51 UTC, dieriba commented on backend/windmill-api/src/database_triggers/trigger.rs
> +    tokio::spawn(async move {
is it really needed as we expect to last forever as long as the server is running, also we have a channel on it so we can kill that future when we to.
Asking it to know why would it be preferable to await the future as you suggest ?

2025-01-22 08:24 UTC, HugoCasa commented on backend/windmill-api/src/database_triggers/trigger.rs
> +    tokio::spawn(async move {
@dieriba the function start_database doesn't contain any await statements so it doesn't need to be async
(just realized i did the same with the other triggers)

2025-01-22 08:36 UTC, HugoCasa commented on backend/windmill-api/src/postgres_triggers/handler.rs
> +    transaction_to_track: Vec<String>,
why not just use an enum?

2025-01-22 08:37 UTC, hugocasa commented on backend/windmill-api/src/postgres_triggers/hex.rs
missing the link to the original code for this one

2025-01-22 10:39 UTC, dieriba commented on backend/windmill-api/src/postgres_triggers/handler.rs
> +    transaction_to_track: Vec<String>,
because I wanted to handle more specific case, for example the length of the vector, or duplicate element inside it, as well as the error message to output if one those error were to be found.

2025-01-23 17:26 UTC, hugocasa commented on frontend/src/lib/script_helpers.ts
> +		database?: {
postgres

2025-01-23 17:26 UTC, HugoCasa commented on frontend/src/lib/script_helpers.ts
> +		database?: {
postgres

2025-01-24 12:25 UTC, HugoCasa commented on backend/.vscode/settings.json
> +  "rust-analyzer.cargo.features": ["postgres_trigger"]
please remove it, will affect all devs
you can put in it in the top level .vscode/settings.json which is gitignored

2025-01-24 12:29 UTC, HugoCasa approved these changes

2025-01-24 14:12 UTC, merged