WIP: fetch raw values
windmill-labs/windmill pull request #4866
Opened 2024-12-06 15:30 UTC by uael

2024-12-06 16:44 UTC, uael commented on backend/windmill-queue/src/jobs.rs
> +                Some(value.clone())
No clone

2024-12-09 18:32 UTC, uael commented on backend/windmill-common/src/cache.rs
> +                fs::import_or_insert_with(&key.path(&Path::new(self.root)), with)
Just self.root

2024-12-09 18:32 UTC, uael commented on backend/windmill-common/src/auth.rs
> +        return Ok(true);
Re-add

2024-12-09 18:32 UTC, uael commented on backend/windmill-common/src/cache.rs
>                          lock AS \"lock: String\", \
Indent

2024-12-09 18:32 UTC, uael commented on backend/windmill-common/src/cache.rs
>                  sqlx::query!(
Just Arc::new

2024-12-09 18:32 UTC, uael commented on backend/windmill-common/src/cache.rs
> +                    "Invalid job payload job kind: {:?}",
payload for* job kind

2024-12-09 18:32 UTC, uael commented on backend/windmill-worker/src/worker_flow.rs
> +    if matches!(flow_job.job_kind, JobKind::Flow) {
Check if this mutation is really necessary; same_worker can be taken from job and skipping the preprocessor can be done later on based on this same next condition

2024-12-11 12:06 UTC, uael commented on backend/windmill-queue/src/jobs.rs
> +                cache::flow::fetch_version_lite(_db, version).await
add fallback to no lite

2024-12-11 12:31 UTC, uael commented on backend/windmill-worker/src/common.rs
>  ) -> String {
Remove the else if let None

2024-12-12 00:36 UTC, uael commented on backend/windmill-worker/src/worker.rs
> +    let (raw_script, metadata) = cache::script::fetch(db, *script_hash).await?;
raw_script -> data

2024-12-12 00:36 UTC, uael commented on backend/windmill-worker/src/worker.rs
> +            // FIXME(uael): If found no usage of `JobKind::DeploymentCallback` as a job,
I* found

2024-12-12 10:27 UTC, HugoCasa requested changes

2024-12-12 10:27 UTC, HugoCasa commented on backend/windmill-queue/src/jobs.rs
> +                None
if !apply_preprocessor, you should remove preprocessor from the flow status

2024-12-12 10:27 UTC, HugoCasa commented on backend/windmill-queue/src/jobs.rs
> +                JobKind::FlowPreview,
should use JobKind::Flow

2024-12-12 21:20 UTC, uael commented on backend/windmill-queue/src/jobs.rs
> +                JobKind::FlowPreview,
Flow

2024-12-12 21:20 UTC, uael commented on backend/windmill-queue/src/jobs.rs
> +                None, // `raw_flow` is fetched on pull.
Check version as well

2024-12-13 11:14 UTC, uael commented on backend/windmill-worker/src/csharp_executor.rs
> +        requirements_o.map(|x| x.as_str()).unwrap_or("")
Good bot

2024-12-13 11:19 UTC, uael commented on backend/windmill-worker/src/csharp_executor.rs
> +        requirements_o.unwrap_or(&String::new())
Nope

2024-12-16 07:26 UTC, uael commented
In handle_flow_dependencies, move `tx.commit().await?;` before the lite version insertion

2024-12-16 16:10 UTC, merged